# 로컬 개발용 infra
services:
  db:
    image: postgres:16
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql/mount:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - api-net

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - api-net

networks:
  api-net:
    name: hwachang-api