version: "3.7"
services:
  spring:
    container_name: spring
    image: yoonyounghun/hwachang-api
    ports:
      - "8080:8080"
    volumes:
      - /var/log/:/logs/
    depends_on:
      - redis
    networks:
      - api-net
      -
  db:
    image: postgres:16
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql/mount:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hwachang
      - POSTGRES_PASSWORD=hwachang
    networks:
      - api-net

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - api-net

networks:
  api-net:
    name: hwachang-api